//===--- tesseract.h - Tesseract Drawing/Rendering Functions ----*- C++ -*-===//
//
//                              MC 4D Renderer
//                        Michael Layzell - CISC 454
//                        Queen's University - W2015
//
//===----------------------------------------------------------------------===//

#ifndef __tesseract_h
#define __tesseract_h

#include "gl.h"
#include <glm/fwd.hpp>

struct Tesseract {
  // There are 24 faces on a tesseract
  static const size_t FACE_COUNT = 24;
  static glm::vec4 faces[FACE_COUNT * 4];

  // They are generated by the gen() function;
  static void gen();
};


#endif // defined(__tesseract_h)
