//===--- tesseract.h - Tesseract Drawing/Rendering Functions ----*- C++ -*-===//
//
//                              MC 4D Renderer
//                        Michael Layzell - CISC 454
//                        Queen's University - W2015
//
//===----------------------------------------------------------------------===//

#ifndef __tesseract_h
#define __tesseract_h

#include "gl.h"
#include <glm/fwd.hpp>

struct Tesseract {
  // There are 24 faces on a tesseract
  static const size_t FACE_COUNT = 24;
  static const size_t FACE_SIZE = 4;
  static const size_t FACES_SIZE = FACE_COUNT * FACE_SIZE;
  static glm::vec4 faces[FACES_SIZE];
  static GLuint VAO;

  // They are generated by the gen() function;
  static void gen();

  static const size_t OUT_SIZE = FACE_COUNT * 6;
  static void withOffset(glm::vec4 offset, glm::vec4 *out);

  static const size_t LINES_SIZE = FACE_COUNT * 8;
  static void linesWithOffset(glm::vec4 offset, glm::vec4 *out);
};


#endif // defined(__tesseract_h)
